
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import javax.swing.JTable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TFMaMi = new javax.swing.JTextField();
        TFHarga = new javax.swing.JTextField();
        TFNama = new javax.swing.JTextField();
        jDate = new com.toedter.calendar.JDateChooser();
        BTSave = new javax.swing.JButton();
        BTClear = new javax.swing.JButton();
        BTHapus = new javax.swing.JButton();
        BTPrint = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Niagara Solid", 0, 60)); // NOI18N
        jLabel1.setText("APLIKASI KASIR");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 20, 480, 60);

        jLabel2.setText("Copyright 2017");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(680, 80, 90, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 780, 0);

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));
        jPanel2.setLayout(null);

        jLabel3.setText("Tanggal");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 20, 60, 20);

        jLabel4.setText("Makanan / Minuman");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 80, 120, 20);

        jLabel5.setText("Harga");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 140, 50, 20);

        jLabel6.setText("Atas Nama");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 200, 80, 20);
        jPanel2.add(TFMaMi);
        TFMaMi.setBounds(10, 100, 240, 30);
        jPanel2.add(TFHarga);
        TFHarga.setBounds(10, 160, 240, 30);
        jPanel2.add(TFNama);
        TFNama.setBounds(10, 220, 240, 30);
        jPanel2.add(jDate);
        jDate.setBounds(10, 40, 240, 30);

        BTSave.setText("Save");
        BTSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSaveActionPerformed(evt);
            }
        });
        jPanel2.add(BTSave);
        BTSave.setBounds(20, 273, 90, 30);

        BTClear.setText("Clear");
        BTClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTClearActionPerformed(evt);
            }
        });
        jPanel2.add(BTClear);
        BTClear.setBounds(180, 273, 90, 30);

        BTHapus.setText("Delete");
        BTHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTHapusActionPerformed(evt);
            }
        });
        jPanel2.add(BTHapus);
        BTHapus.setBounds(20, 323, 90, 30);

        BTPrint.setText("Print");
        BTPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTPrintActionPerformed(evt);
            }
        });
        jPanel2.add(BTPrint);
        BTPrint.setBounds(180, 323, 90, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 120, 300, 410);

        jPanel3.setBackground(new java.awt.Color(255, 204, 51));
        jPanel3.setForeground(new java.awt.Color(255, 255, 51));
        jPanel3.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Stencil", 0, 60)); // NOI18N
        jLabel7.setText("APLIKASI KASIR");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 20, 620, 70);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 760, 100);

        jPanel4.setBackground(new java.awt.Color(255, 255, 153));
        jPanel4.setLayout(null);

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tanggal", "Makanan / Minuman", "Harga", "Nama"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table1);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 430, 402);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(330, 120, 440, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTHapusActionPerformed

    private void BTSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(jDate.getDate());
        
        String SQL = "INSERT INTO kasir{Tanggal, Makanan, Harga, Nama}"
                + "VALUES('"+jDate.getDate()+"','"+TFMaMi.getText()+"',"+TFHarga.getText()+"','"+TFNama.getText()+"')";
        
        
    }//GEN-LAST:event_BTSaveActionPerformed

    private void BTPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Transaksi Toko A");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        
        try{
            Table1.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
            
        } catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print", e.getMessage());
        }
        
        
    }//GEN-LAST:event_BTPrintActionPerformed

    private void BTClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTClearActionPerformed
        // TODO add your handling code here:
        TFMaMi.setText("");
        TFHarga.setText("");
        TFNama.setText("");
    }//GEN-LAST:event_BTClearActionPerformed

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
        // TODO add your handling code here:
        int baris = Table1.getSelectedRow();
        
        if(baris != -1)
        {
        jDate.setDateFormatString(Table1.getValueAt(baris, 0).toString());
        TFMaMi.setText(Table1.getValueAt(baris, 1).toString());
        TFHarga.setText(Table1.getValueAt(baris, 2).toString());
        TFNama.setText(Table1.getValueAt(baris, 3).toString());
        
        }
    }//GEN-LAST:event_Table1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTClear;
    private javax.swing.JButton BTHapus;
    private javax.swing.JButton BTPrint;
    private javax.swing.JButton BTSave;
    private javax.swing.JTextField TFHarga;
    private javax.swing.JTextField TFMaMi;
    private javax.swing.JTextField TFNama;
    private javax.swing.JTable Table1;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
